version: 0.2


phases:
  pre_build:
    commands:
       - mkdir build_dir
  build:
    commands:
      - echo "Build started on" >> src/build_dir
  post_build:
    commands:
      - tar -cf newfile.tar.gz build_dir
artifacts:
    files: newfile.tar.gz 
