version: '0.2'
phases:
  install:
    runtime-versions:
      python: '3.8'
  pre_build:
    commands:  []
  build:
    commands:
      - python -m venv python_venv
      - source python_venv/bin/activate
      - cd codepipeline
      - pip install -r requirements.txt
      - mkdir lib
      - mkdir -p lib
      - mv instantclient_19_3/* lib/.
      - rm -rf instantclient_19_3
      - zip -r lambda-function.zip *
      - mkdir -p ./dist && mv lambda-function.zip ./dist
artifacts:
  files: '**/*'
  base-directory: artifacts
